version: "3.6"
services:
    app:
        build:
            context: ./docker/php
            args:
                - TZ=${TZ}
        container_name: laravel_app
        volumes:
            - ./src:/work
            - ./logs:/work/storage/logs
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        working_dir: /work
        environment:
            - APP_LOG_DIR=${APP_LOG_DIR}
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_DATABASE=${DB_NAME}
            - DB_USERNAME=${DB_USER}
            - DB_PASSWORD=${DB_PASS}
            - TZ=${TZ}
            - MAIL_HOST=${MAIL_HOST}
            - MAIL_PORT=${MAIL_PORT}
            - HTTP_PROXY=${PROXY}
            - HTTPS_PROXY=${PROXY}
    web:
        image: nginx:1.17-alpine
        container_name: laravel_web
        depends_on:
            - app
        ports:
            - 10080:80
        volumes:
            - ./src:/work
            - ./logs:/var/log/nginx
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        environment:
            - TZ=${TZ}
    mail:
        image: mailhog/mailhog
        container_name: laravel_mail
        ports:
            - ${MAILHOG_PORT}:8025
    db:
        image: mysql:8.0
        container_name: laravel_db
        ports:
            - ${DB_PORT}:3306
        volumes:
            - db-store:/var/lib/mysql
            - ./logs:/var/log/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        environment:
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASS}
            - MYSQL_ROOT_PASSWORD=${DB_PASS}
            - TZ=${TZ}
networks: 
    default:
        external: 
            name: wp_network
volumes:
    db-store: